"""expand password column length

Revision ID: f95ed77f04f5
Revises: 8d3db8b99af8
Create Date: 2025-11-10 13:54:56.619666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95ed77f04f5'
down_revision: Union[str, Sequence[str], None] = '8d3db8b99af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("password", type_=sa.String(length=255))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
